
import React, { useState, useEffect } from 'react';
import type { BlogPost } from '../types';
import { generateBlogContent } from '../services/geminiService';

const SkeletonCard: React.FC = () => (
  <div className="bg-white rounded-lg p-8 border border-gray-200 animate-pulse">
    <div className="h-6 bg-gray-200 rounded w-3/4 mb-4"></div>
    <div className="space-y-2">
      <div className="h-4 bg-gray-200 rounded"></div>
      <div className="h-4 bg-gray-200 rounded w-5/6"></div>
      <div className="h-4 bg-gray-200 rounded w-3/4"></div>
    </div>
  </div>
);

const Insights: React.FC = () => {
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchContent = async () => {
      try {
        setIsLoading(true);
        setError(null);
        const generatedPosts = await generateBlogContent();
        setPosts(generatedPosts);
      } catch (err) {
        setError('Failed to load insights. Please try refreshing the page.');
        console.error(err);
      } finally {
        setIsLoading(false);
      }
    };

    fetchContent();
  }, []);

  return (
    <section id="insights" className="py-20 bg-white">
      <div className="container mx-auto px-6">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <h2 className="text-3xl md:text-4xl font-bold text-[#160578] mb-4">
            Latest AI-Powered Insights
          </h2>
          <p className="text-lg text-gray-600">
            Fresh perspectives on the future of microfinance, generated by our AI.
          </p>
        </div>
        <div className="grid md:grid-cols-3 gap-8">
          {isLoading && (
            <>
              <SkeletonCard />
              <SkeletonCard />
              <SkeletonCard />
            </>
          )}
          {error && <p className="text-red-500 text-center col-span-3">{error}</p>}
          {!isLoading && !error && posts.map((post, index) => (
            <div key={index} className="bg-gray-50 rounded-lg p-8 border border-gray-200 transition-all duration-300 hover:shadow-lg hover:border-[#ff8600]">
              <h3 className="text-xl font-bold text-[#160578] mb-3">{post.title}</h3>
              <p className="text-gray-600">{post.summary}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Insights;
